[versions]
kotest = "6.0.7"
kotlin = "2.3.0"
kotlin-logging = "7.0.14"
kotlinx-coroutines = "1.10.2"
kover = "0.9.4"
logback = "1.5.24"
system-lambda = "1.2.1"
z3-turnkey = "4.14.1"

[libraries]
kotest-assertions-table = { module = "io.kotest:kotest-assertions-table", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
system-lambda = { module = "com.github.stefanbirkner:system-lambda", version.ref = "system-lambda" }
z3-turnkey = { module = "tools.aqua:z3-turnkey", version.ref = "z3-turnkey" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
